---
url_api:    https://api.flipdot.org/
wait_days: 14

mail:
    server:
        fqdn:       mail.example.org
        port:       587
        user:       username
        password:   $ecre7
    sender:
        name:       Franz Flipflop
        address:    fff@example.org
    recipient:
        name:       Herr Getraenk
        address:    hg@ic.ht
    text:
        subject1:   Getränkebestellung №
        subject2:   für flipdot e.V.
        body:       |
                    Lieber Chief Executive of Boozyness,

                    bitte überprüfe folgende automatisierte Bestellung auf Richtigkeit. Sollte ein
                    Fehler passiert sein, antworte auf diese E-Mail (an
                    drinks-storage@example.org). Sollte alles richtig sein, entferne diesen
                    einleitenden Text und leite die E-Mail über den Forward-Button deines
                    Mailclients an folgende Adressen weiter.

                      drinks-storage@example.org
                      herr-getraenk@example.org

                    Somit ist garantiert, dass alle Personen die über obige E-Mail-Adresse
                    informiert werden im Fall einer korrekten oder fehlerhaften Bestellung.

                    Zur Überprüfung der Bestellung können die erfassten aktuellen Daten verwendet
                    werden. Sollten Daten nicht aktuell genug sein, wird keine Bestellung
                    ausgelöst. Diese sind auch in den Statistiken als abrubt verschwundene Balken
                    zu erkennen.

                    https://stats.flipdot.org/dashboard/db/drinks-storage

                    Die Einstellungen des Programms was diese Mail abgesendet hat ist unter folgender URL einsehbar.
                    Davon ausgenommen sind personalisierte Daten.

                    https://github.com/flipdot/drinks-storage-order/blob/master/config.yaml

                    Vielen Dank,
                      Drinks Storage

                    -- 

                    Sehr geehrter Herr Getränk,

                    hiermit geben wir bei Ihnen die Bestellung im Anhang auf.

                    Mit besten Grüßen,
                      i.A. Franz Flipflop
                      für flipdot e.V.

template:
    sender:
        logo:       \input{logo/flipdot-logo.pdf_tex}
        email:      drinks@flipdot.org
        person:     Franz Flipflop
        phone:      0800 / 111 0 111
        name:       flipdot e.V.
        address:  |
                  | Franz-Ulrich-Straße 18
                  | 34117 Kassel
        place:      Kassel
    supplier:     |
                  | Irgendein Getränkemarkt
                  | Straßenname 123
                  | 12345 Stadt

limits:
    min_crates: 20
    max_crates: 40

demand:
    apfelschorle:        4
    grapefruit_sprudel:  4
    mineralwasser:       2
    becks:               4
    eschweger:           5
    jacobinus:           5
    jever:               4
    jever_fun:           3
    koestritzer:         2
    radler:              2
    mio_banane:          3
    mio_cola:            7
    mio_ginger:          7
    mio_mate:            9
...
