---
url_api:    https://api.flipdot.org/
wait_days: 14

mail:
    server:
        fqdn:       mail.example.org
        port:       587
        user:       username
        password:   $ecre7
    sender:
        name:       Franz Flipflop
        address:    fff@example.org
    recipient:
        name:       Herr Getraenk
        address:    hg@ic.ht
    text:
        subject1:   Getränkebestellung №
        subject2:   für flipdot e.V.
        body:       |
                    Sehr geehrter Herr Getränk,

                    hiermit geben wir bei Ihnen die Bestellung im Anhang auf.

                    Mit besten Grüßen,
                      i.A. Franz Flipflop
                      für flipdot e.V.

template:
    sender:
        logo:       \input{logo/flipdot-logo.pdf_tex}
        email:      drinks@flipdot.org
        person:     Franz Flipflop
        phone:      0800 / 111 0 111
        name:       flipdot e.V.
        address:  |
                  | Franz-Ulrich-Straße 18
                  | 34117 Kassel
        place:      Kassel
    supplier:     |
                  | Irgendein Getränkemarkt
                  | Straßenname 123
                  | 12345 Stadt

limits:
    min_crates: 20
    max_crates: 40

demand:
    apfelschorle:        4
    grapefruit_sprudel:  4
    mineralwasser:       2
    becks:               4
    eschweger:           5
    jacobinus:           5
    jever:               4
    jever_fun:           3
    koestritzer:         2
    radler:              2
    mio_banane:          3
    mio_cola:            7
    mio_ginger:          7
    mio_mate:            7
...
